// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZe9jsR-v7c-FwF-1U2yUPPTJBrgUmpnc',
    appId: '1:157770815332:web:4ad7a5e9086c6e956a8c71',
    messagingSenderId: '157770815332',
    projectId: 'ncast-app',
    authDomain: 'ncast-app.firebaseapp.com',
    storageBucket: 'ncast-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyZ7b8byJK0E0geyYeeXnH45uqBfs0Dc',
    appId: '1:157770815332:android:660ecde1190f87c36a8c71',
    messagingSenderId: '157770815332',
    projectId: 'ncast-app',
    storageBucket: 'ncast-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5bflvpGXC8pt69S5HEqiC_9jSKEjeing',
    appId: '1:157770815332:ios:3f67b3cdc8404dcb6a8c71',
    messagingSenderId: '157770815332',
    projectId: 'ncast-app',
    storageBucket: 'ncast-app.appspot.com',
    iosBundleId: 'com.example.ncast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5bflvpGXC8pt69S5HEqiC_9jSKEjeing',
    appId: '1:157770815332:ios:3f67b3cdc8404dcb6a8c71',
    messagingSenderId: '157770815332',
    projectId: 'ncast-app',
    storageBucket: 'ncast-app.appspot.com',
    iosBundleId: 'com.example.ncast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZe9jsR-v7c-FwF-1U2yUPPTJBrgUmpnc',
    appId: '1:157770815332:web:8e9157896f920d526a8c71',
    messagingSenderId: '157770815332',
    projectId: 'ncast-app',
    authDomain: 'ncast-app.firebaseapp.com',
    storageBucket: 'ncast-app.appspot.com',
  );
}
